### ISSUE TITLE
Incorrect email or password

### ISSUE THREAD

**Issue by maxneuds** [ggogel/seafile-containerized#3]
I run a fresh container (I use caddy as proxy) and it boots up fine.
Then I want to login with the predefined admin mail and password but in response I get `Incorrect email or password` any idea how this happens and how to fix or look into it for a fix?

---

After a container restart I get `Page unavailable` after login.
Something I found while looking at the container output:

```
2021-01-27 18:28:04 3 [Warning] Aborted connection 3 to db: 'unconnected' user: 'root' host: '172.20.0.1' (Got an error reading communication packets)
```

**Comment by ggogel** [comment]
Thanks for the issue report. I've deployed a new test envorinment myself today and encountered the same issue. I'll publish a fix later today or tomorrow.

**Comment by maxneuds** [comment]
If I find anything or can help somehow, then feel free to hit me up.

**Comment by ggogel** [comment]
I should've properly tested the initial deployment 😅 It turned out that the script, which creates the user, was never executed. I've implemented this into the seahub service now. This also means that the two environment variables for the admin credentials have to be defined there now. I've successfully tested it in my environment. Can you check if it works for you too? The fix is in seahub-8.0.2_006 and seafile-server-8.0.2_005.

**Comment by maxneuds** [comment]
First run still the same. At least I get a more precise error now during the second run.
```
seahub_1          | Error happened during creating seafile admin.
```
Maybe I updated wrong? I deleted the volumes, the images and the container and did a fresh `docker-compose up`. `docker image ls` says created 8 hours ago. I am still not well into Docker so maybe I am missing something?

**Comment by ggogel** [comment]
Did you put the credentials into quotation marks maybe? Try to not set the variables and it should default to me@example.com and asecret, which you can change afterwards.

**Comment by maxneuds** [comment]
No quotation marks. I also kept `DB_HOST=db` and `DB_ROOT_PASSWD=db_dev` sinice it's isolated in its own network anyways (well done btw, didn't know about this). I use it with https but this shouldn't  affect admin account creation.

**Comment by ggogel** [comment]
Yes, the db password strength shouldn't matter in such enclosed environments.

Maybe it's some kind of symbol in the password that is parsed incorrectly. Did you check if it works without setting the variables and logging in with the default one? You could then create a second admin with the mail and password you wanted, log in with that and delete the other one. I'm not able to reproduce the issue anymore. I tried setting both mail and password, only mail or none of both and they all worked.

**Comment by maxneuds** [comment]
I will try with default next. That's what my compose looks like at the moment:

```
version: '3.8'
services:
  seafile-server:
    image: ggogel/seafile-server:8.0.2
    volumes:
      - seafile-data:/shared
    environment:
      - DB_HOST=db
      - DB_ROOT_PASSWD=db_dev
      - TIME_ZONE=Europe/Berlin
      - SEAFILE_ADMIN_EMAIL=me@mine.tld
      - SEAFILE_ADMIN_PASSWORD=asecret
      - HTTPS=true # Set this to true if you plan to use a reverse proxy with HTTPS. Can be changed later in the admin settings on the web-ui.
      - SEAFILE_SERVER_HOSTNAME=files.mine.tld # Mandatory on first deployment!
    depends_on:
      - db
      - memcached
      - seafile-caddy
    networks:
      - seafile-net

  seahub:
    image: ggogel/seahub:8.0.2
    volumes:
      - seafile-data:/shared
      - seahub-avatars:/shared/seafile/seahub-data/avatars
      - seahub-custom:/shared/seafile/seahub-data/custom
    depends_on:
      - seafile-server
      - seafile-caddy
    networks:
      - seafile-net

  seahub-media:
    image: ggogel/seahub-media:8.0.2
    volumes:
     - seahub-avatars:/usr/share/caddy/media/avatars
     - seahub-custom:/usr/share/caddy/media/custom
    depends_on:
      - seafile-server
      - db
      - memcached
      - seafile-caddy
    networks:
      - seafile-net

  db:
    image: mariadb:10.5.8
    environment:
      - MYSQL_ROOT_PASSWORD=db_dev
      - MYSQL_LOG_CONSOLE=true
    volumes:
      - seafile-mariadb:/var/lib/mysql
    networks:
      - seafile-net

  memcached:
    image: memcached:1.6.9
    entrypoint: memcached -m 1024
    networks:
      - seafile-net

  seafile-caddy:
    image: ggogel/seafile-caddy:1.0.0
    #ports:
    #  - 80:80 # Point your reverse proxy to port 80 of this service
    networks:
      - seafile-net
      - caddy
    labels:
      caddy: files.neuds.eu #this will automatically enable https and Let's Encrypt
      caddy.reverse_proxy: "{{upstreams 80}}"
      # only during first run
      #caddy.tls.ca: https://acme-staging-v02.api.letsencrypt.org/directory

networks:
  seafile-net:
    internal: true
  caddy:
    name: caddy

volumes:
  seafile-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/docker/.data/seafile/data'
  seafile-mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/docker/.data/seafile/mariadb'
  seahub-avatars:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/docker/.data/seafile/avatars'
  seahub-custom:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/docker/.data/seafile/seahub'
```

Basically environment variable changes and bindings to local folders.

**Comment by ggogel** [comment]
You have to define `SEAFILE_ADMIN_EMAIL` and `SEAFILE_ADMIN_PASSWORD` on seahub now.

**Comment by maxneuds** [comment]
Got in with the defaults, deleted the user and created a new admin. :)
That solves it. Perfectly working now. Very nice containerized. Thanks!
